### ISSUE TITLE
Are we collecting money now ?

### ISSUE THREAD

**Issue by marcandregirard** [banane-io/PDB#36]
We need to implement the resources system. We could start by implementing some basic resources: wood, stone, (animal/food), iron, gold and copper.  We will need a way to generate those resources for the player to collect them. I think we could tie the availability of the resource with terrain type (Forest generate wood, mountain stone etc.). We need a way for the player to gather them (that could be tie with the hero issue). We need a way to transport/store the resources on the player hero and maybe a way to store them (like a building in the base, when the issue is complete).
- [ ] Define resource
- [ ] generate resources
- [ ] gathering
- [ ] storing
- For the moment, we could make everything replenish-able, maybe some day we could have a limit on resources (like stone is 5000/moutain).

*\* I leave a lot of freedom on the conception, do your best and to be afraid to test a new concept. We can always remake things later.

**Comment by mrheaumeproulx** [comment]
Should we specify the type of resources gathering?

Here's my reasoning, for example, in order to gather food in your base, you have 5 options available: Fishing, Hunting, Livestock, Farms and *Herbalism*(Food from forest) . 5 different methods of gathering resources. Let's say there's an event going on or the players obtains a bonus that provides food gathered from wilderness x2. That means Fishing, Hunting and *Herbalism* would gather x2 more food than Farm and Livestock.

(Concept could be applied to much than just resources but in our current iteration, only resources is concerned)

**Comment by marcandregirard** [comment]
https://chat.stackoverflow.com/rooms/44914/conversation/resources-conversation

Small conversation about resources management

**Comment by marcandregirard** [comment]
This has been done in an initial way.
