### ISSUE TITLE
Player show page

### ISSUE THREAD

**Issue by LepageT** [banane-io/PDB#43]
When viewing the info of a player, the hero show the reference (#Entity:0x007f97486a73b8) instead of the info of the hero.

**Comment by marcandregirard** [comment]
Yeah I did not take the time to render the entity fragment. When I notice the problem the first I did not take the time to fix this since, the player view will probably not be the hero information page. The player view should be used for the account settings for the game. The hero should not be displayed there.

**Comment by marcandregirard** [comment]
This is not a bug anymore since this is not implemented in the java version.
