### ISSUE TITLE
Find a way to create to have an admin user for the first installation.

### ISSUE THREAD

**Issue by marcandregirard** [banane-io/PDB#48]
We have a little problem at the moment. The controller that edit user is authorize for modification for anyone. That permit anybody to promote them to the admin role. We need to find a way to either have a default account that would be an admin and use that account to modify the real admin of the site or we find an alternative solution (I don't have anything else at the moment).

Share your ideas!

**Comment by Mirv** [comment]
I'm going to field this one too.

Since you don't have any cross/join tables setup to allow users to participate in multiple games & don't have a dashboard setup for users to select which player they controlling, I'm going to go with there will be one game (for now) & eventually we will wrap that game in a handling system to spawn multiple copies.

So we will use a master admin who will have permission to make other admins etc.  Then there will be a before_action hook that checks all edit/update/destroy actions with a method `.admin?` which will probably have a cancancan/pundit helper to check the role.

**Comment by Mirv** [comment]
inserted

`, dependent: :destroy`

To players, entities & users to honor the foreign keys.

```
EntitiesControllerTest: test_should_destroy_entity
--------------------------------------------------
  Entity Load (1.2ms)  SELECT  "entities".* FROM "entities" WHERE "entities"."id" = 1 LIMIT 1
  User Load (1.2ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = 135138680 LIMIT 1
   (1.0ms)  SELECT COUNT(*) FROM "entities"
Processing by EntitiesController#destroy as HTML
  Parameters: {"id"=>"1"}
  User Load (1.5ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = 135138680  ORDER BY "users"."id" ASC LIMIT 1
  Entity Load (1.3ms)  SELECT  "entities".* FROM "entities" WHERE "entities"."id" = 1 LIMIT 1
  Savepoint (0.7ms)  SAVEPOINT active_record_1
  Player Load (8.6ms)  SELECT  "players".* FROM "players" WHERE "players"."entity_id" = 1 LIMIT 1
  User Load (14.3ms)  SELECT  "users".* FROM "users" WHERE "users"."player_id" = 1 LIMIT 1
  SQL (15.9ms)  DELETE FROM "users" WHERE "users"."id" = 135138680
  Savepoint (17.0ms)  ROLLBACK TO SAVEPOINT active_record_1
Completed 500 Internal Server Error in 2752ms (ActiveRecord: 59.4ms)
```

Resulting error summary...

```
Finished in 11.005418s, 0.6361 runs/s, 0.9086 assertions/s.

  1) Error:
EntitiesControllerTest#test_should_destroy_entity:
Java::JavaLang::StackOverflowError: 
   
7 runs, 10 assertions, 0 failures, 1 errors, 0 skips
```

**Comment by marcandregirard** [comment]
There is no admin part in the Java version yet, so I'll be closing this issue since it's not relevant anymore.
