### ISSUE TITLE
How are we managing resources

### ISSUE THREAD

**Issue by mrheaumeproulx** [banane-io/PDB#50]
How do we manage resources in the game? I came up with two options:
1: Resources are associated the the player.
2. Resources are associated to an entity (ex: a base)

Pros & Cons: Resources associated to player
- Resources are managed at a single place
- All sources of resources are calculated into a single global resources
- Easier management of resources

Pros & Cons: Resources associated to entity
- Multiple entities resources to manage (multiple bases with their set of resources)
- More complex system
- Opens up a more tactical approach to the game. (ex: if base1 doesn't  have enough resources, send resources from base2 to base1)

What are your thoughts?
If you have other options, don't hesitate to tell us about it.

**Comment by mrheaumeproulx** [comment]
I vote for second option as of now. I think managing resources on multiple entities could open up some gameplay options, but I don't know it it would be too complex for the player and make it less fun too play.

**Comment by marcandregirard** [comment]
Option 2 is the best since option 1 is so simple that it would not scaled very well. With option 2 we have a better way to make things interesting. We could have certain way to merge resources from multiple sources. I think that in issue #36  I did not specifically talk about this aspect, but the building hint was to have resources not tied to the user directly. @LepageT what do you think ?
