### ISSUE TITLE
Grid not loading the the data for the onClick event

### ISSUE THREAD

**Issue by marcandregirard** [banane-io/PDB#7]
There seems to be a bug sometime, where there is not data in the gron array or the events does not work. A simple refresh fix it, but it should works all the time.

**Comment by mrheaumeproulx** [comment]
Alright I Know the problem. Made some personal test to find the problem. I noticed that the grid.js is getting initialize when on the home page.

OK then, should be working in the grid page then. But when I switched, it wasn't initialized. Deduced there were some kind of ajax calls somewhere and yep the app is using turbolinks.

Because there is no grid in home on documentready, it can't attribute events to the grid. This is why a refresh makes the grid work because it reinitialize the js and the grid is present at that moment.

To resolve the problem, after a little research, i included a gem called jquery-turbolinks and added the js in application.js. 

But then the gon wasn't initialized. To make gon work we need to include the tag <% include_gon &> in views where gon is used.

Question is do we keep turbolinks or not :P

**Comment by marcandregirard** [comment]
I need to read about what turbolink is doing because everything things don't make sense for me at the moment. Why would the grid not be there at document ready because of turbolink ? I'll need to know/see what step did you take to find all that information. At the moment, I don't understand and I don't like that :P !

**Comment by marcandregirard** [comment]
I've take a bit of time at work to read on turbolinks and we do not need it at all. It does things we don't need and is shacky with his integration to Jquery. Turbolinks helps when you have big pages with a lot of JS and CSS (which we do not have at the moment). So we should deactivate it. The principle of turbolinks is not what we need at the moment (replacing the current page keeping all the js and css loaded, but replacing the content). If we ever needed to speed pages loading times we should re-evalutate it, but for the moment let's deactivate it.
